/**
 * Thí nghiệm gợi ý theo từng bài — Hoá 11 Kết nối tri thức.
 *
 * Đối chiếu SGK ngày 27/09/2026 (thầy Văn yêu cầu) qua các trang giải SGK chép
 * lại đề mục thí nghiệm (vietjack, loigiaihay, hoc24, vndoc…; mỗi mục ít nhất hai
 * nguồn khớp nhau trừ khi ghi khác) — URL trong báo cáo. `sgkTrang` = thí nghiệm
 * có trong SGK ở trang đó; không có `sgkTrang` = gợi ý thêm ngoài sách.
 *
 * Soạn ngày 27/09/2026 (AI soạn theo nội dung bài, chủ dự án yêu cầu), CHƯA qua
 * giáo viên duyệt: mọi mục `daDuyet: false` và giao diện hiện nhãn "Chờ giáo
 * viên duyệt". Thầy duyệt xong thì đổi đúng mục đó thành `true`.
 * Báo cáo soát: docs/soat-hoa-hoc/2026-09-27-thi-nghiem-theo-bai.md
 *
 * Số trang lấy theo các trang giải SGK, chưa đối chiếu sách giấy.
 * Luật an toàn: thí nghiệm SGK có chất độc / ăn mòn để `phong-thi-nghiem` như
 * sách — thầy Văn đồng ý ngày 27/09/2026 (chủ dự án chuyển lời) — kèm cảnh báo
 * và yêu cầu giáo viên hướng dẫn. Thí nghiệm NGOÀI sách có chất độc
 * (Cu + HNO₃, SO₂ + Br₂, NH₃ + HCl…) vẫn để `giao-vien-bieu-dien`. `tai-nha` chỉ dùng thứ ăn được / đồ gia dụng an toàn.
 * Tệp riêng, KHÔNG gộp vào constants.ts (tệp đó do máy sinh).
 */

/** `sgk-mo-ta`: SGK chỉ MÔ TẢ thí nghiệm để học sinh đọc và trả lời câu hỏi
 *  (nitro hoá benzene, cộng Cl₂ vào benzene…) — không phải bài tự làm. */
export type NoiLam = 'phong-thi-nghiem' | 'giao-vien-bieu-dien' | 'tai-nha' | 'sgk-mo-ta';

/** Mô phỏng tương tác trong tab Thí nghiệm có thể mở thẳng từ thẻ. */
export type MoPhong = 'den-dien-li' | 'chuan-do' | 'dien-li-nhieu-nac';

export interface ThiNghiem {
  id: string;
  lessonId: string;
  ten: string;
  mucDich: string;
  hoaChat: string[];
  dungCu: string[];
  cachLam: string[];
  hienTuong: string;
  giaiThich: string;
  anToan: string[];
  noiLam: NoiLam;
  moPhong?: MoPhong;
  /** Trang SGK có thí nghiệm này; bỏ trống = gợi ý thêm ngoài sách. */
  sgkTrang?: number;
  daDuyet: boolean;
}

export const TEN_NOI_LAM: Record<NoiLam, string> = {
  'phong-thi-nghiem': 'Phòng thí nghiệm',
  'giao-vien-bieu-dien': 'Giáo viên biểu diễn',
  'tai-nha': 'Làm được ở nhà',
  'sgk-mo-ta': 'SGK mô tả — đọc / xem video',
};

export const THI_NGHIEM: ThiNghiem[] = [
  /* ── Chương 1 ─────────────────────────────────────────────────────────── */
  {
    id: 'b1-no2-nhiet-do', lessonId: 'bai-1', sgkTrang: 10,
    ten: 'Ảnh hưởng của nhiệt độ đến cân bằng 2NO₂ ⇌ N₂O₄',
    mucDich: 'Quan sát cân bằng chuyển dịch khi đổi nhiệt độ.',
    hoaChat: ['Ba ống nghiệm chứa khí NO₂, nút kín, màu như nhau'],
    dungCu: ['Cốc nước đá', 'Cốc nước nóng'],
    cachLam: ['Ống 1 để so sánh; ngâm ống 2 vào nước đá, ống 3 vào nước nóng khoảng 1–2 phút.', 'So màu ba ống.'],
    hienTuong: 'Ống ngâm nước đá nhạt màu hơn ống so sánh; ống ngâm nước nóng nâu đỏ đậm hơn.',
    giaiThich: '2NO₂ (nâu đỏ) ⇌ N₂O₄ (không màu), chiều thuận toả nhiệt. Hạ nhiệt độ: cân bằng chuyển dịch theo chiều toả nhiệt (tạo N₂O₄) nên nhạt màu; tăng nhiệt độ: chuyển dịch theo chiều thu nhiệt (tạo NO₂) nên đậm màu.',
    anToan: ['NO₂ rất độc: chỉ dùng ống đã nút kín, không mở ống.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b1-ch3coona-nhiet-do', lessonId: 'bai-1', sgkTrang: 11,
    ten: 'Ảnh hưởng của nhiệt độ đến cân bằng thuỷ phân CH₃COONa',
    mucDich: 'Quan sát cân bằng CH₃COONa + H₂O ⇌ CH₃COOH + NaOH chuyển dịch theo nhiệt độ.',
    hoaChat: ['Dung dịch CH₃COONa 0,5 M', 'Phenolphthalein'],
    dungCu: ['Ba ống nghiệm', 'Cốc nước đá', 'Cốc nước nóng'],
    cachLam: ['Thêm 1–2 giọt phenolphthalein vào khoảng 10 mL CH₃COONa, chia đều vào ba ống.', 'Ống 1 để so sánh; ngâm ống 2 vào nước đá, ống 3 vào nước nóng rồi so màu.'],
    hienTuong: 'Ống ngâm nước nóng hồng đậm hơn; ống ngâm nước đá nhạt màu hơn ống so sánh.',
    giaiThich: 'CH₃COONa + H₂O ⇌ CH₃COOH + NaOH, chiều thuận thu nhiệt. Đun nóng: cân bằng chuyển dịch theo chiều thuận, tạo thêm OH⁻ nên hồng đậm hơn; làm lạnh thì ngược lại.',
    anToan: ['Dùng nước nóng vừa phải, cầm ống nghiệm bằng kẹp gỗ.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b1-ch3coona-nong-do', lessonId: 'bai-1', sgkTrang: 12,
    ten: 'Ảnh hưởng của nồng độ đến cân bằng thuỷ phân CH₃COONa',
    mucDich: 'Quan sát cân bằng chuyển dịch khi thêm chất phản ứng hoặc sản phẩm.',
    hoaChat: ['Dung dịch CH₃COONa có phenolphthalein (màu hồng nhạt)', 'Tinh thể CH₃COONa', 'Dung dịch CH₃COOH'],
    dungCu: ['Ba ống nghiệm'],
    cachLam: ['Chia dung dịch vào ba ống. Ống 1 để so sánh; ống 2 thêm vài tinh thể CH₃COONa; ống 3 thêm vài giọt CH₃COOH.'],
    hienTuong: 'Ống 2 hồng đậm hơn; ống 3 nhạt màu hơn ống so sánh.',
    giaiThich: 'Tăng nồng độ CH₃COONa: cân bằng chuyển dịch theo chiều thuận, tạo thêm OH⁻. Thêm CH₃COOH (sản phẩm): cân bằng chuyển dịch theo chiều nghịch, OH⁻ giảm.',
    anToan: ['Hoá chất loãng, an toàn với găng và kính thông thường.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b2-dan-dien', lessonId: 'bai-2', sgkTrang: 16,
    ten: 'Thử tính dẫn điện — chất điện li mạnh, yếu, không điện li',
    mucDich: 'Phân biệt chất điện li và chất không điện li; so sánh chất điện li mạnh với yếu (SGK trang 16–18).',
    hoaChat: ['Nước cất', 'Muối ăn khan và dung dịch NaCl', 'Dung dịch HCl, NaOH, saccharose, ethanol', 'Dung dịch HCl 0,1 M và CH₃COOH 0,1 M'],
    dungCu: ['Bộ thử tính dẫn điện (nguồn, bóng đèn, hai điện cực)', 'Cốc thuỷ tinh'],
    cachLam: ['Nhúng điện cực lần lượt vào từng mẫu, đóng mạch, quan sát bóng đèn.', 'Rửa điện cực bằng nước cất trước khi chuyển sang mẫu khác.'],
    hienTuong: 'Nước cất, muối ăn khan: đèn không sáng; dung dịch NaCl, HCl, NaOH: đèn sáng. Saccharose, ethanol: không sáng. Cùng 0,1 M, đèn ở cốc HCl sáng hơn cốc CH₃COOH.',
    giaiThich: 'Dung dịch dẫn điện nhờ ion chuyển động. NaCl rắn có ion nhưng bị giữ chặt trong tinh thể; tan trong nước (dung môi phân cực) thì ion tách ra và di chuyển được. HCl phân li hoàn toàn, CH₃COOH chỉ phân li một phần nên ít ion hơn.',
    anToan: ['Dùng nguồn điện an toàn của phòng thí nghiệm, không cắm điện lưới trực tiếp.', 'Không chạm điện cực khi đang đóng mạch.'],
    noiLam: 'phong-thi-nghiem', moPhong: 'den-dien-li', daDuyet: false,
  },
  {
    id: 'b2-chat-chi-thi', lessonId: 'bai-2', sgkTrang: 23,
    ten: 'Tự làm chất chỉ thị từ hoa đậu biếc hoặc bắp cải tím',
    mucDich: 'Làm chất chỉ thị pH tự nhiên và thử với đồ dùng trong nhà.',
    hoaChat: ['Hoa đậu biếc (khoảng 50 g) hoặc bắp cải tím thái nhỏ (khoảng 100 g)', 'Giấm, nước rửa bát, nước soda, nước muối, viên sủi vitamin C'],
    dungCu: ['Cốc 250 mL', 'Nước sôi', 'Rây lọc'],
    cachLam: ['Ngâm hoa hoặc bắp cải trong khoảng 100 mL nước sôi chừng 10 phút, lọc lấy nước màu.', 'Nhỏ nước màu vào từng mẫu, so màu (nếu có giấy pH thì đo pH để đối chiếu).'],
    hienTuong: 'Môi trường acid (giấm, nước vitamin C) cho màu đỏ – hồng; trung tính giữ màu tím hoặc xanh ban đầu; môi trường base (nước rửa bát, soda) chuyển xanh – xanh lục.',
    giaiThich: 'Sắc tố anthocyanin đổi cấu tạo (và màu) theo pH, giống cách quỳ tím đổi màu.',
    anToan: ['Người lớn hỗ trợ khi dùng nước sôi.', 'Không nếm các mẫu đã pha.'],
    noiLam: 'tai-nha', daDuyet: false,
  },
  {
    id: 'b2-thuy-phan-muoi', lessonId: 'bai-2', sgkTrang: 24,
    ten: 'Đo pH dung dịch muối — sự thuỷ phân của ion',
    mucDich: 'Thấy dung dịch muối có thể mang môi trường base hoặc acid.',
    hoaChat: ['Dung dịch Na₂CO₃', 'Dung dịch AlCl₃', 'Dung dịch FeCl₃', 'Giấy pH'],
    dungCu: ['Ống nghiệm', 'Đũa thuỷ tinh'],
    cachLam: ['Dùng đũa thuỷ tinh chấm từng dung dịch lên giấy pH, so với bảng màu.'],
    hienTuong: 'Na₂CO₃ cho pH lớn hơn 7; AlCl₃ và FeCl₃ cho pH nhỏ hơn 7.',
    giaiThich: 'CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻ nên Na₂CO₃ có môi trường base. Al³⁺ + H₂O ⇌ Al(OH)²⁺ + H⁺ (Fe³⁺ tương tự) nên AlCl₃, FeCl₃ có môi trường acid.',
    anToan: ['FeCl₃ làm ố da và quần áo; rửa tay sau thí nghiệm.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b2-chuan-do', lessonId: 'bai-2', sgkTrang: 25,
    ten: 'Thực hành chuẩn độ acid – base',
    mucDich: 'Xác định nồng độ dung dịch NaOH (khoảng 0,1 M) bằng dung dịch HCl 0,1 M đã biết nồng độ.',
    hoaChat: ['Dung dịch HCl 0,1 M', 'Dung dịch NaOH nồng độ khoảng 0,1 M', 'Dung dịch phenolphthalein'],
    dungCu: ['Pipette 10 mL', 'Burette 25 mL', 'Bình tam giác 100 mL', 'Bình tia nước cất', 'Giá đỡ, kẹp burette'],
    cachLam: [
      'Dùng pipette lấy 10 mL dung dịch HCl 0,1 M cho vào bình tam giác, thêm 1–2 giọt phenolphthalein.',
      'Cho dung dịch NaOH vào burette, chỉnh về vạch 0.',
      'Mở khoá, nhỏ từng giọt NaOH xuống bình, vừa nhỏ vừa lắc đều.',
      'Dừng khi dung dịch xuất hiện màu hồng nhạt bền khoảng 10 giây. Ghi thể tích NaOH; làm ít nhất ba lần.',
    ],
    hienTuong: 'Dung dịch không màu; tới điểm cuối, một giọt NaOH làm xuất hiện màu hồng nhạt bền.',
    giaiThich: 'HCl + NaOH → NaCl + H₂O. Tại điểm tương đương n(NaOH) = n(HCl) = 0,1 × 0,010 = 0,001 mol, nên C(NaOH) = 0,001 : V(NaOH, lít).',
    anToan: ['Đeo kính bảo hộ: NaOH gây bỏng mắt.', 'Không hút pipette bằng miệng — dùng quả bóp.'],
    noiLam: 'phong-thi-nghiem', moPhong: 'chuan-do', daDuyet: false,
  },
  {
    id: 'b2-dien-li-nhieu-nac', lessonId: 'bai-2',
    ten: 'Điện li nhiều nấc (mô phỏng, mở rộng)',
    mucDich: 'Mở rộng ngoài SGK: vì sao nấc sau luôn yếu hơn nấc trước.',
    hoaChat: ['Mô phỏng: H₂SO₄, H₂SO₃, H₂CO₃, H₃PO₄'],
    dungCu: ['Máy tính / máy chiếu'],
    cachLam: ['Chọn một acid, kéo nồng độ từ lớn xuống nhỏ, theo dõi nồng độ từng tiểu phân và độ điện li mỗi nấc.'],
    hienTuong: 'Pha loãng thì độ điện li của các nấc chưa hoàn toàn tăng; [H⁺] thực tế nhỏ hơn số nấc × C.',
    giaiThich: 'SGK KNTT chỉ xếp H₂SO₄ vào nhóm acid mạnh, không học điện li nhiều nấc hay hằng số Ka. Khi làm bài tập theo SGK và đề thi, H₂SO₄ loãng được coi là điện li hoàn toàn ([H⁺] = 2C).',
    anToan: ['Mô phỏng — không dùng hoá chất.'],
    noiLam: 'phong-thi-nghiem', moPhong: 'dien-li-nhieu-nac', daDuyet: false,
  },

  /* ── Chương 2 ─────────────────────────────────────────────────────────── */
  {
    id: 'b5-nhan-biet-nh4', lessonId: 'bai-5', sgkTrang: 36,
    ten: 'Nhận biết ion ammonium trong phân đạm',
    mucDich: 'Nhận biết muối ammonium bằng dung dịch kiềm.',
    hoaChat: ['Phân bón potassium nitrate (KNO₃)', 'Phân bón ammonium chloride (NH₄Cl)', 'Dung dịch NaOH 20 %', 'Giấy pH'],
    dungCu: ['Hai ống nghiệm', 'Kẹp gỗ', 'Đèn cồn', 'Bình tia nước cất'],
    cachLam: ['Cho khoảng 1 g mỗi loại phân vào một ống, thêm khoảng 3 mL nước, lắc tan.', 'Thêm khoảng 1 mL NaOH 20 % vào mỗi ống, đun nhẹ; đưa mẩu giấy pH ướt lên miệng ống.'],
    hienTuong: 'Ống NH₄Cl có khí mùi khai, giấy pH chỉ môi trường base; ống KNO₃ không có hiện tượng đó.',
    giaiThich: 'NH₄Cl + NaOH → NaCl + NH₃↑ + H₂O (đun nóng). Chỉ muối ammonium mới giải phóng NH₃ khi đun với kiềm — đó là dấu hiệu nhận biết ion NH₄⁺.',
    anToan: ['Đeo kính bảo hộ: NaOH 20 % nóng bắn vào mắt rất nguy hiểm.', 'Hướng miệng ống ra xa người; không ngửi trực tiếp — phẩy nhẹ tay cho hơi bay tới mũi.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b5-nh3-hcl', lessonId: 'bai-5',
    ten: 'NH₃ gặp HCl tạo "khói trắng"',
    mucDich: 'Minh hoạ tính base của ammonia ở thể khí (SGK chỉ nêu phương trình, không có thí nghiệm).',
    hoaChat: ['Dung dịch NH₃ đặc', 'Dung dịch HCl đặc'],
    dungCu: ['Hai đũa thuỷ tinh', 'Tủ hút'],
    cachLam: ['Nhúng một đũa vào dung dịch NH₃ đặc, đũa kia vào HCl đặc.', 'Đưa hai đầu đũa lại gần nhau (không chạm).'],
    hienTuong: 'Xuất hiện khói trắng giữa hai đầu đũa.',
    giaiThich: 'NH₃(g) + HCl(g) → NH₄Cl(s): các hạt NH₄Cl rắn rất nhỏ tạo thành "khói" trắng.',
    anToan: ['Khí NH₃ và HCl đều cay, độc — làm trong tủ hút, không ngửi trực tiếp.'],
    noiLam: 'giao-vien-bieu-dien', daDuyet: false,
  },
  {
    id: 'b6-cu-hno3', lessonId: 'bai-6',
    ten: 'Copper tác dụng với nitric acid đặc',
    mucDich: 'Minh hoạ tính oxi hoá mạnh của HNO₃ (SGK Bài 6 không có thí nghiệm này).',
    hoaChat: ['Mảnh copper', 'HNO₃ đặc'],
    dungCu: ['Ống nghiệm', 'Tủ hút', 'Bông tẩm NaOH đậy miệng ống'],
    cachLam: ['Giáo viên cho mảnh Cu vào ống nghiệm chứa ít HNO₃ đặc, đậy bông tẩm NaOH.'],
    hienTuong: 'Khí màu nâu đỏ thoát ra; dung dịch chuyển xanh lục (pha loãng thì thành xanh lam).',
    giaiThich: 'Cu + 4HNO₃(đặc) → Cu(NO₃)₂ + 2NO₂↑ + 2H₂O. NO₂ màu nâu đỏ; ion Cu²⁺ màu xanh lam, lẫn NO₂ hoà tan nên dung dịch đặc trông xanh lục.',
    anToan: ['NO₂ rất độc, HNO₃ đặc gây bỏng nặng: CHỈ giáo viên làm trong tủ hút, hoặc xem video.'],
    noiLam: 'giao-vien-bieu-dien', daDuyet: false,
  },
  {
    id: 'b7-s-fe', lessonId: 'bai-7', sgkTrang: 44,
    ten: 'Sulfur tác dụng với sắt',
    mucDich: 'Chứng minh sulfur có tính oxi hoá.',
    hoaChat: ['Bột sulfur', 'Bột sắt (trộn theo tỉ lệ khối lượng khoảng 1 : 1,5)'],
    dungCu: ['Ống nghiệm khô chịu nhiệt', 'Nút bông', 'Đèn cồn', 'Kẹp ống nghiệm'],
    cachLam: ['Cho khoảng 2 g hỗn hợp bột vào ống nghiệm, nút bông.', 'Hơ nóng đều ống rồi đun tập trung vào chỗ có hỗn hợp.'],
    hienTuong: 'Sulfur nóng chảy, hỗn hợp cháy sáng, toả nhiều nhiệt, tạo chất rắn màu đen.',
    giaiThich: 'Fe + S → FeS (t°). Sulfur nhận electron (0 → −2) nên là chất oxi hoá; sắt là chất khử.',
    anToan: ['Phản ứng toả nhiệt mạnh; có thể sinh ít SO₂: làm nơi thoáng, hướng miệng ống ra xa người.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b7-s-o2', lessonId: 'bai-7', sgkTrang: 45,
    ten: 'Sulfur tác dụng với oxygen',
    mucDich: 'Chứng minh sulfur có tính khử.',
    hoaChat: ['Bột sulfur', 'Bình khí oxygen'],
    dungCu: ['Muôi sắt cắm qua nút cao su', 'Đèn cồn'],
    cachLam: ['Đun sulfur trong muôi sắt tới khi nóng chảy và cháy một phần trong không khí.', 'Đưa nhanh muôi vào bình oxygen.'],
    hienTuong: 'Trong không khí, sulfur cháy với ngọn lửa nhỏ màu xanh nhạt; trong oxygen cháy mãnh liệt hơn.',
    giaiThich: 'S + O₂ → SO₂ (t°). Sulfur nhường electron (0 → +4) nên là chất khử.',
    anToan: ['SO₂ sinh ra độc, gây ho: làm trong tủ hút hoặc nơi thật thoáng, có giáo viên hướng dẫn.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b7-so2-bromine', lessonId: 'bai-7',
    ten: 'SO₂ làm mất màu nước bromine',
    mucDich: 'Minh hoạ tính khử của SO₂ (SGK dùng ví dụ khác, không có thí nghiệm này).',
    hoaChat: ['Khí SO₂ (điều chế sẵn trong bình kín)', 'Nước bromine loãng'],
    dungCu: ['Ống dẫn khí', 'Ống nghiệm', 'Tủ hút'],
    cachLam: ['Giáo viên dẫn khí SO₂ vào ống nghiệm chứa nước bromine màu vàng.'],
    hienTuong: 'Nước bromine nhạt dần rồi mất màu.',
    giaiThich: 'SO₂ + Br₂ + 2H₂O → H₂SO₄ + 2HBr. Sulfur từ +4 lên +6: SO₂ là chất khử.',
    anToan: ['SO₂ và bromine đều độc: chỉ giáo viên làm trong tủ hút, hoặc xem video.'],
    noiLam: 'giao-vien-bieu-dien', daDuyet: false,
  },
  {
    id: 'b8-cu-h2so4', lessonId: 'bai-8', sgkTrang: 51,
    ten: 'Copper tác dụng với sulfuric acid đặc, nóng',
    mucDich: 'Thấy H₂SO₄ đặc có tính oxi hoá mạnh: oxi hoá cả kim loại đứng sau hydrogen.',
    hoaChat: ['Lá đồng cắt nhỏ', 'Dung dịch H₂SO₄ 70 %', 'Bông tẩm dung dịch NaOH loãng'],
    dungCu: ['Ống nghiệm', 'Kẹp gỗ', 'Đèn cồn'],
    cachLam: ['Cho vài lá đồng nhỏ vào ống nghiệm, thêm khoảng 3 mL H₂SO₄ 70 %, nút miệng ống bằng bông tẩm NaOH.', 'Hơ nóng đều ống rồi đun tập trung ở đáy ống.'],
    hienTuong: 'Đồng tan dần, dung dịch chuyển xanh, có khí thoát ra.',
    giaiThich: 'Cu + 2H₂SO₄(đặc) → CuSO₄ + SO₂↑ + 2H₂O (t°). Bông tẩm NaOH giữ lại khí SO₂ độc: SO₂ + 2NaOH → Na₂SO₃ + H₂O.',
    anToan: ['H₂SO₄ đặc nóng gây bỏng rất nặng, SO₂ độc: làm dưới sự giám sát trực tiếp của giáo viên, đeo kính và găng.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b8-hao-nuoc', lessonId: 'bai-8', sgkTrang: 51,
    ten: 'Tính háo nước của sulfuric acid đặc',
    mucDich: 'Quan sát H₂SO₄ đặc lấy nước của hợp chất hữu cơ.',
    hoaChat: ['Đường mía (khoảng 10 g)', 'H₂SO₄ đặc (khoảng 2 mL)'],
    dungCu: ['Cốc thuỷ tinh 100 mL', 'Tủ hút'],
    cachLam: ['Cho đường vào cốc, nhỏ đều H₂SO₄ đặc lên bề mặt đường.'],
    hienTuong: 'Đường hoá đen, sủi bọt, khối than xốp dâng cao trào khỏi cốc; cốc nóng lên.',
    giaiThich: 'C₁₂H₂₂O₁₁ → 12C + 11H₂O (H₂SO₄ đặc hút nước). Một phần carbon bị H₂SO₄ đặc oxi hoá: C + 2H₂SO₄ → CO₂ + 2SO₂ + 2H₂O — khí sinh ra làm khối than phồng lên.',
    anToan: ['H₂SO₄ đặc gây bỏng rất nặng, SO₂ độc: làm trong tủ hút, có giáo viên hướng dẫn, đeo kính và găng.', 'Pha loãng H₂SO₄ đặc: rót từ từ ACID vào NƯỚC, không làm ngược lại.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b8-nhan-biet-so4', lessonId: 'bai-8', sgkTrang: 53,
    ten: 'Nhận biết ion sulfate SO₄²⁻',
    mucDich: 'Nhận biết muối sulfate và sulfuric acid bằng ion Ba²⁺.',
    hoaChat: ['Dung dịch Na₂SO₄', 'Dung dịch BaCl₂', 'Dung dịch H₂SO₄ loãng (để dự đoán, đối chiếu)'],
    dungCu: ['Ống nghiệm'],
    cachLam: ['Nhỏ vài giọt BaCl₂ vào khoảng 1 mL Na₂SO₄, lắc nhẹ.', 'Dự đoán rồi thử với H₂SO₄ loãng.'],
    hienTuong: 'Xuất hiện kết tủa trắng (cả với H₂SO₄ loãng).',
    giaiThich: 'Ba²⁺ + SO₄²⁻ → BaSO₄↓ trắng. BaSO₄ không tan cả trong acid — nhỏ thêm HCl loãng thấy kết tủa không tan, phân biệt được với BaCO₃, BaSO₃.',
    anToan: ['Hợp chất barium tan đều độc: không để dính tay, rửa tay sau thí nghiệm.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },

  /* ── Chương 3 ─────────────────────────────────────────────────────────── */
  {
    id: 'b11-chung-cat', lessonId: 'bai-11', sgkTrang: 64,
    ten: 'Chưng cất ethanol từ rượu',
    mucDich: 'Tách ethanol khỏi hỗn hợp ethanol – nước bằng chưng cất.',
    hoaChat: ['Khoảng 60 mL rượu nấu thủ công', 'Đá bọt'],
    dungCu: ['Bình cầu có nhánh 250 mL', 'Nhiệt kế', 'Ống sinh hàn nước', 'Ống đong 50 mL', 'Bình tam giác', 'Bếp điện hoặc đèn cồn'],
    cachLam: ['Cho rượu và đá bọt vào bình cầu (không quá 2/3 bình), lắp nhiệt kế và ống sinh hàn.', 'Đun từ từ, theo dõi nhiệt kế; khi nhiệt độ bắt đầu tăng trở lại thì ngừng đun.'],
    hienTuong: 'Nhiệt độ đứng yên một thời gian trong khi chất lỏng ngưng tụ chảy xuống bình hứng; sản phẩm có độ cồn cao hơn rượu ban đầu.',
    giaiThich: 'Ethanol sôi ở nhiệt độ thấp hơn nước nên bay hơi trước, ngưng tụ ở ống sinh hàn. Nhiệt độ sôi: ethanol < hỗn hợp < nước.',
    anToan: ['Ethanol dễ cháy: ưu tiên bếp điện, không để lửa gần đầu ra ống sinh hàn.', 'Luôn cho đá bọt để tránh sôi trào; không đun cạn bình.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b11-chiet', lessonId: 'bai-11', sgkTrang: 66,
    ten: 'Chiết β-carotene từ nước ép cà rốt',
    mucDich: 'Tách chất hữu cơ bằng chiết lỏng – lỏng.',
    hoaChat: ['20 mL nước ép cà rốt', '20 mL hexane'],
    dungCu: ['Phễu chiết 60 mL', 'Giá đỡ', 'Cốc'],
    cachLam: ['Cho nước ép cà rốt và hexane vào phễu chiết, đậy nút, lắc khoảng 2 phút rồi để yên khoảng 5 phút.', 'Mở nút đậy, mở khoá xả lớp nước ở dưới, giữ lại lớp hexane.'],
    hienTuong: 'Hỗn hợp tách hai lớp; lớp hexane ở trên chuyển từ không màu sang vàng cam.',
    giaiThich: 'β-carotene tan tốt trong hexane (không phân cực) hơn trong nước nên chuyển sang lớp hexane; hexane không tan trong nước và nhẹ hơn nên nằm trên.',
    anToan: ['Hexane rất dễ cháy: xa ngọn lửa, làm nơi thoáng.', 'Khi lắc, thỉnh thoảng dốc ngược phễu và mở khoá để xả hơi, tránh bật nút.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b11-ket-tinh', lessonId: 'bai-11', sgkTrang: 68,
    ten: 'Tinh chế đường đỏ thành đường trắng',
    mucDich: 'Tìm hiểu phương pháp kết tinh.',
    hoaChat: ['Đường đỏ', 'Nước', 'Than hoạt tính'],
    dungCu: ['Cốc', 'Phễu lọc', 'Bếp đun'],
    cachLam: ['SGK mô tả: hoà đường đỏ vào nước nóng, thêm than hoạt tính để khử màu, lọc bỏ than, cô bớt nước rồi để nguội cho đường kết tinh.'],
    hienTuong: 'Thu được tinh thể đường trắng.',
    giaiThich: 'Than hoạt tính hấp phụ chất màu. Độ tan của đường giảm khi nguội nên đường kết tinh, tạp chất còn lại trong nước.',
    anToan: ['Cẩn thận với nước đường nóng — dễ gây bỏng.'],
    noiLam: 'sgk-mo-ta', daDuyet: false,
  },
  {
    id: 'b11-sac-ki-giay', lessonId: 'bai-11',
    ten: 'Sắc kí giấy với mực bút dạ',
    mucDich: 'Tách các chất màu trong mực bằng phương pháp sắc kí (SGK chỉ nêu lí thuyết sắc kí cột).',
    hoaChat: ['Bút dạ màu đen hoặc nâu (loại tan trong nước)', 'Nước'],
    dungCu: ['Giấy lọc cà phê hoặc giấy thấm', 'Cốc', 'Kẹp'],
    cachLam: ['Chấm một chấm mực đậm cách mép giấy khoảng 2 cm.', 'Treo giấy sao cho mép nhúng vào nước, chấm mực nằm TRÊN mặt nước.', 'Chờ nước ngấm lên khoảng 10 phút.'],
    hienTuong: 'Chấm mực loang thành các dải màu khác nhau ở các độ cao khác nhau.',
    giaiThich: 'Mỗi chất màu bị giấy (pha tĩnh) giữ lại và bị nước (pha động) kéo đi ở mức khác nhau, nên đi được quãng đường khác nhau và tách ra.',
    anToan: ['An toàn — dùng đồ gia dụng.'],
    noiLam: 'tai-nha', daDuyet: false,
  },

  /* ── Chương 4 ─────────────────────────────────────────────────────────── */
  {
    id: 'b15-hexane-bromine', lessonId: 'bai-15', sgkTrang: 86,
    ten: 'Phản ứng bromine hoá hexane',
    mucDich: 'Quan sát phản ứng thế halogen của alkane khi đun nóng.',
    hoaChat: ['Hexane', 'Nước bromine'],
    dungCu: ['Ống nghiệm', 'Cốc nước ấm khoảng 50 °C'],
    cachLam: ['Cho khoảng 1 mL hexane và 1 mL nước bromine vào ống nghiệm: hỗn hợp tách hai lớp.', 'Lắc, rồi đặt ống nghiệm vào cốc nước ấm khoảng 50 °C.'],
    hienTuong: 'Ở nhiệt độ thường gần như không đổi; khi ngâm nước ấm, màu vàng của bromine nhạt dần rồi mất.',
    giaiThich: 'C₆H₁₄ + Br₂ → C₆H₁₃Br + HBr (phản ứng thế, giả thiết chỉ thế một nguyên tử H). Alkane chỉ thế halogen khi có nhiệt hoặc ánh sáng.',
    anToan: ['Hexane dễ cháy: tuyệt đối xa ngọn lửa, dùng nước ấm chứ không đun trực tiếp.', 'Bromine độc, ăn da: làm nơi thoáng hoặc tủ hút, đeo găng.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b15-oxi-hoa-hexane', lessonId: 'bai-15', sgkTrang: 88,
    ten: 'Phản ứng oxi hoá hexane',
    mucDich: 'Thấy alkane bền với chất oxi hoá ở điều kiện thường nhưng cháy được.',
    hoaChat: ['Hexane', 'Dung dịch KMnO₄ loãng'],
    dungCu: ['Ống nghiệm', 'Bát sứ', 'Que đóm'],
    cachLam: ['Nhỏ hexane vào ống nghiệm chứa dung dịch KMnO₄, lắc.', 'Cho một ít hexane vào bát sứ, đưa que đóm đang cháy lại gần.'],
    hienTuong: 'KMnO₄ giữ nguyên màu tím. Hexane trong bát sứ bốc cháy với ngọn lửa màu vàng.',
    giaiThich: 'Alkane không phản ứng với KMnO₄ ở điều kiện thường. Khi cháy hoàn toàn: 2C₆H₁₄ + 19O₂ → 12CO₂ + 14H₂O; thiếu oxygen thì tạo CO.',
    anToan: ['Đốt trong bát sứ, lượng nhỏ, không dùng cốc thuỷ tinh; để xa chai hexane.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b16-ethylene', lessonId: 'bai-16', sgkTrang: 99,
    ten: 'Điều chế và thử tính chất ethylene',
    mucDich: 'Điều chế C₂H₄ từ ethanol; thử phản ứng cộng, phản ứng oxi hoá và phản ứng cháy.',
    hoaChat: ['Cồn 96°', 'H₂SO₄ đặc', 'Đá bọt', 'Nước bromine loãng', 'Dung dịch KMnO₄ loãng'],
    dungCu: ['Bình cầu 250 mL', 'Ống dẫn khí', 'Ống nghiệm', 'Đèn cồn'],
    cachLam: ['Rót từ từ H₂SO₄ đặc vào cồn có đá bọt rồi đun nóng.', 'Dẫn khí lần lượt qua nước bromine và dung dịch KMnO₄, sau đó đốt khí ở đầu ống dẫn.'],
    hienTuong: 'Nước bromine và KMnO₄ nhạt dần rồi mất màu; khí cháy với ngọn lửa sáng, toả nhiều nhiệt.',
    giaiThich: 'C₂H₅OH → CH₂=CH₂ + H₂O (H₂SO₄ đặc, khoảng 170 °C). CH₂=CH₂ + Br₂ → CH₂Br–CH₂Br. KMnO₄ oxi hoá liên kết đôi. C₂H₄ + 3O₂ → 2CO₂ + 2H₂O.',
    anToan: ['H₂SO₄ đặc gây bỏng nặng; ethylene dễ cháy nổ: làm dưới sự hướng dẫn trực tiếp của giáo viên, đeo kính và găng.', 'Luôn cho đá bọt để tránh sôi trào; tháo ống dẫn ra khỏi dung dịch trước khi tắt đèn để không bị hút ngược.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b16-acetylene', lessonId: 'bai-16', sgkTrang: 99,
    ten: 'Điều chế và thử tính chất acetylene',
    mucDich: 'Điều chế C₂H₂ từ đất đèn; thử phản ứng cộng, phản ứng oxi hoá và phản ứng cháy.',
    hoaChat: ['Đất đèn (CaC₂)', 'Nước', 'Nước bromine loãng', 'Dung dịch KMnO₄ loãng'],
    dungCu: ['Bình cầu có nhánh', 'Phễu nhỏ giọt', 'Ống nghiệm', 'Tủ hút'],
    cachLam: ['Nhỏ từ từ nước xuống đất đèn.', 'Dẫn khí vào nước bromine và dung dịch KMnO₄, sau đó đốt khí.'],
    hienTuong: 'Có khí thoát ra; nước bromine và KMnO₄ mất màu; khí cháy sáng, có muội đen.',
    giaiThich: 'CaC₂ + 2H₂O → Ca(OH)₂ + C₂H₂↑. C₂H₂ + 2Br₂ → CHBr₂–CHBr₂. Tỉ lệ C cao nên cháy có muội. Nhận biết C₂H₂ bằng AgNO₃/NH₃ (kết tủa vàng AgC≡CAg) là kiến thức lí thuyết trong bài, không nằm trong thí nghiệm này.',
    anToan: [
      'C₂H₂ rất dễ cháy nổ; bromine độc: làm dưới sự hướng dẫn trực tiếp của giáo viên, xa mọi nguồn lửa trừ lúc đốt khí.',
      'CaC₂ kĩ thuật lẫn tạp chất nên khí sinh ra có PH₃, H₂S độc (mùi tỏi): làm trong tủ hút.',
    ],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b16-chuoi-chin', lessonId: 'bai-16',
    ten: 'Ethylene làm quả chín nhanh',
    mucDich: 'Thấy vai trò của ethylene (khí do quả chín tiết ra) trong đời sống.',
    hoaChat: ['Hai quả chuối xanh (hoặc bơ, cà chua xanh)', 'Một quả táo hoặc chuối đã chín'],
    dungCu: ['Hai túi giấy'],
    cachLam: ['Túi 1: chuối xanh + quả chín. Túi 2: chỉ chuối xanh. Gấp kín miệng túi.', 'Để 2–3 ngày rồi so sánh.'],
    hienTuong: 'Chuối trong túi có quả chín vàng nhanh hơn rõ rệt.',
    giaiThich: 'Quả chín tiết ra khí ethylene (CH₂=CH₂) — hormone thực vật thúc quả chín; túi kín giữ khí lại.',
    anToan: ['An toàn — ăn được sau thí nghiệm.'],
    noiLam: 'tai-nha', daDuyet: false,
  },
  {
    id: 'b17-nitro-hoa-benzene', lessonId: 'bai-17', sgkTrang: 105,
    ten: 'Phản ứng nitro hoá benzene',
    mucDich: 'Tìm hiểu phản ứng thế ở vòng benzene tạo nitrobenzene.',
    hoaChat: ['Benzene', 'HNO₃ đặc', 'H₂SO₄ đặc'],
    dungCu: ['Bình cầu, ống sinh hàn hồi lưu', 'Nồi cách thuỷ', 'Phễu chiết'],
    cachLam: ['SGK mô tả: trộn HNO₃ đặc với H₂SO₄ đặc đã làm lạnh, thêm benzene, đun cách thuỷ khoảng 80 °C trong thời gian dài, rồi cho vào phễu chiết.'],
    hienTuong: 'Chất lỏng tách hai lớp; lớp nitrobenzene là chất lỏng màu vàng nhạt.',
    giaiThich: 'C₆H₆ + HNO₃ → C₆H₅NO₂ + H₂O (H₂SO₄ đặc, t°). Nhóm –NO₂ thế một nguyên tử H của vòng.',
    anToan: ['Benzene gây ung thư, hỗn hợp acid đặc rất nguy hiểm: học sinh chỉ đọc mô tả hoặc xem video.'],
    noiLam: 'sgk-mo-ta', daDuyet: false,
  },
  {
    id: 'b17-cong-chlorine', lessonId: 'bai-17', sgkTrang: 106,
    ten: 'Phản ứng cộng chlorine vào benzene',
    mucDich: 'Thấy benzene cũng cộng được, nhưng cần điều kiện mạnh (ánh sáng).',
    hoaChat: ['Benzene', 'Khí chlorine'],
    dungCu: ['Bình nón đậy kín'],
    cachLam: ['SGK mô tả: dẫn một ít Cl₂ vào bình chứa benzene, đậy kín rồi đưa ra ánh nắng.'],
    hienTuong: 'Có khói trắng và lớp bột trắng bám vào thành bình.',
    giaiThich: 'C₆H₆ + 3Cl₂ → C₆H₆Cl₆ (ánh sáng). Sản phẩm hexachlorocyclohexane từng dùng làm thuốc trừ sâu "666", nay đã cấm.',
    anToan: ['Benzene và chlorine đều rất độc: chỉ đọc mô tả hoặc xem video.'],
    noiLam: 'sgk-mo-ta', daDuyet: false,
  },
  {
    id: 'b17-toluene-kmno4', lessonId: 'bai-17', sgkTrang: 107,
    ten: 'Oxi hoá toluene và benzene bằng KMnO₄',
    mucDich: 'So sánh tính bền của vòng benzene với nhánh alkyl của toluene.',
    hoaChat: ['Benzene', 'Toluene', 'Dung dịch KMnO₄ loãng', 'Dung dịch H₂SO₄ loãng'],
    dungCu: ['Ống nghiệm', 'Nồi cách thuỷ', 'Tủ hút'],
    cachLam: ['Hai ống nghiệm, mỗi ống 1 mL KMnO₄ và 1 mL H₂SO₄ loãng; ống 1 thêm 1 mL benzene, ống 2 thêm 1 mL toluene.', 'Lắc rồi ngâm cả hai ống trong nồi nước nóng.'],
    hienTuong: 'Ống benzene vẫn giữ màu tím; ống toluene nhạt màu rồi mất màu.',
    giaiThich: 'Vòng benzene bền với chất oxi hoá. Nhánh –CH₃ của toluene bị oxi hoá thành –COOH: 5C₆H₅CH₃ + 6KMnO₄ + 9H₂SO₄ → 5C₆H₅COOH + 3K₂SO₄ + 6MnSO₄ + 14H₂O (Mn²⁺ gần như không màu).',
    anToan: ['Benzene gây ung thư: làm trong tủ hút, lượng nhỏ, có giáo viên hướng dẫn, đeo găng.', 'Toluene dễ cháy — dùng nồi cách thuỷ, không đun trực tiếp.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },

  /* ── Chương 5 ─────────────────────────────────────────────────────────── */
  {
    id: 'b19-thuy-phan', lessonId: 'bai-19', sgkTrang: 114,
    ten: 'Thuỷ phân bromoethane',
    mucDich: 'Chứng minh nguyên tử halogen bị thay bằng nhóm –OH khi đun với kiềm.',
    hoaChat: ['Bromoethane (C₂H₅Br)', 'Dung dịch NaOH 10 %', 'Dung dịch HNO₃', 'Dung dịch AgNO₃ 1 %'],
    dungCu: ['Ống nghiệm', 'Đèn cồn hoặc nồi cách thuỷ', 'Tủ hút'],
    cachLam: [
      'Lắc C₂H₅Br với nước cất: hỗn hợp tách hai lớp (C₂H₅Br ở dưới). Rửa, thử lớp nước bằng AgNO₃ tới khi không còn kết tủa — tức là hết ion halide có sẵn.',
      'Thêm dung dịch NaOH 10 %, đun khoảng 5 phút.',
      'Lấy một ít lớp nước sang ống khác, trung hoà NaOH dư bằng HNO₃, rồi nhỏ AgNO₃ 1 %.',
    ],
    hienTuong: 'Xuất hiện kết tủa màu vàng nhạt.',
    giaiThich: 'C₂H₅Br + NaOH → C₂H₅OH + NaBr (t°). NaBr + AgNO₃ → AgBr↓ (vàng nhạt) + NaNO₃. Phải trung hoà NaOH trước, vì OH⁻ cũng tạo kết tủa với Ag⁺ (Ag₂O nâu đen) làm sai kết quả.',
    anToan: ['C₂H₅Br độc, dễ cháy, sôi ở khoảng 38 °C nên bay hơi mạnh khi đun: làm trong tủ hút, đun nhẹ.', 'Đeo kính khi đun kiềm.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b20-chay', lessonId: 'bai-20', sgkTrang: 124,
    ten: 'Phản ứng cháy của alcohol',
    mucDich: 'Quan sát ethanol cháy — cơ sở dùng cồn làm nhiên liệu.',
    hoaChat: ['Cồn 90°'],
    dungCu: ['Bát sứ', 'Que đóm dài'],
    cachLam: ['Cho khoảng 1 mL cồn vào bát sứ, dùng que đóm dài châm lửa.'],
    hienTuong: 'Cồn cháy với ngọn lửa màu xanh nhạt, gần như không có khói.',
    giaiThich: 'C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O. Phản ứng toả nhiều nhiệt.',
    anToan: ['Ngọn lửa cồn khó thấy dưới ánh sáng mạnh: không rót thêm cồn khi đang cháy, để xa chai cồn.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b20-glycerol-cuoh2', lessonId: 'bai-20', sgkTrang: 125,
    ten: 'Copper(II) hydroxide tác dụng với alcohol đa chức',
    mucDich: 'Nhận biết alcohol có nhiều nhóm –OH kề nhau.',
    hoaChat: ['Dung dịch CuSO₄ 2 %', 'Dung dịch NaOH 10 %', 'Glycerol', 'Ethanol'],
    dungCu: ['Ống nghiệm'],
    cachLam: ['Tạo Cu(OH)₂ ở hai ống: nhỏ NaOH vào CuSO₄.', 'Ống 1 thêm vài giọt ethanol (đối chứng), ống 2 thêm vài giọt glycerol, lắc.'],
    hienTuong: 'Ống ethanol: kết tủa xanh không tan. Ống glycerol: kết tủa tan, dung dịch xanh lam đậm.',
    giaiThich: 'CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄. Glycerol có các nhóm –OH kề nhau tạo phức tan màu xanh lam với Cu(OH)₂; ethanol chỉ có một nhóm –OH nên không tạo được.',
    anToan: ['Đeo kính: NaOH gây bỏng mắt.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b20-ethanol-na', lessonId: 'bai-20',
    ten: 'Ethanol tác dụng với sodium',
    mucDich: 'Chứng minh nguyên tử H trong nhóm –OH của alcohol linh động (SGK nêu phản ứng này ở phần lí thuyết).',
    hoaChat: ['Ethanol khan', 'Mẩu sodium nhỏ bằng hạt đậu'],
    dungCu: ['Ống nghiệm', 'Kẹp', 'Que đóm'],
    cachLam: ['Giáo viên cho mẩu Na vào ống nghiệm chứa ethanol khan.', 'Đưa que đóm đang cháy lại gần miệng ống.'],
    hienTuong: 'Mẩu Na tan dần, sủi bọt khí; khí cháy với tiếng nổ nhỏ.',
    giaiThich: '2C₂H₅OH + 2Na → 2C₂H₅ONa + H₂↑. Phản ứng êm hơn nhiều so với Na + nước.',
    anToan: ['Sodium phản ứng mãnh liệt với nước: chỉ giáo viên cắt và dùng mẩu rất nhỏ.', 'Ethanol dễ cháy — tránh xa ngọn lửa trần.', 'Mẩu Na dư: cho tan hết trong ethanol rồi mới đổ bỏ; không ném vào nước hay thùng rác.'],
    noiLam: 'giao-vien-bieu-dien', daDuyet: false,
  },
  {
    id: 'b21-phenol-naoh', lessonId: 'bai-21', sgkTrang: 131,
    ten: 'Phenol tác dụng với NaOH và Na₂CO₃',
    mucDich: 'Chứng minh phenol có tính acid.',
    hoaChat: ['Dung dịch phenol bão hoà (vẩn đục)', 'Dung dịch NaOH 2 M', 'Dung dịch Na₂CO₃ 2 M'],
    dungCu: ['Ống nghiệm'],
    cachLam: ['Hai ống nghiệm, mỗi ống khoảng 1 mL phenol bão hoà; ống 1 thêm 1 mL NaOH, ống 2 thêm 1 mL Na₂CO₃, lắc.'],
    hienTuong: 'Cả hai ống chuyển từ vẩn đục sang trong suốt.',
    giaiThich: 'C₆H₅OH + NaOH → C₆H₅ONa + H₂O. C₆H₅OH + Na₂CO₃ ⇌ C₆H₅ONa + NaHCO₃. Sodium phenolate tan tốt nên dung dịch trong. Phenol yếu hơn H₂CO₃ nên không phản ứng với NaHCO₃ và không giải phóng CO₂.',
    anToan: ['Phenol độc, gây bỏng da: đeo găng, kính; rửa ngay bằng nhiều nước nếu dính da.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b21-phenol-bromine', lessonId: 'bai-21', sgkTrang: 131,
    ten: 'Phenol tác dụng với nước bromine',
    mucDich: 'Thấy vòng benzene trong phenol được hoạt hoá mạnh bởi nhóm –OH.',
    hoaChat: ['Dung dịch phenol 5 %', 'Nước bromine bão hoà'],
    dungCu: ['Ống nghiệm', 'Tủ hút'],
    cachLam: ['Nhỏ vài giọt nước bromine vào khoảng 1 mL dung dịch phenol, lắc.'],
    hienTuong: 'Nước bromine mất màu, xuất hiện kết tủa trắng.',
    giaiThich: 'C₆H₅OH + 3Br₂ → C₆H₂Br₃OH↓ (2,4,6-tribromophenol, trắng) + 3HBr. Benzene không phản ứng với nước bromine, còn phenol phản ứng ngay ở nhiệt độ thường.',
    anToan: ['Phenol gây bỏng da và độc, bromine độc: làm trong tủ hút, đeo găng.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },

  /* ── Chương 6 ─────────────────────────────────────────────────────────── */
  {
    id: 'b23-trang-bac', lessonId: 'bai-23', sgkTrang: 140,
    ten: 'Oxi hoá aldehyde bằng thuốc thử Tollens',
    mucDich: 'Nhận biết nhóm –CHO bằng phản ứng tráng bạc.',
    hoaChat: ['Dung dịch AgNO₃ 1 %', 'Dung dịch NH₃ 5 %', 'Dung dịch acetaldehyde 5 %'],
    dungCu: ['Ống nghiệm thật sạch', 'Cốc nước nóng 70–80 °C'],
    cachLam: [
      'Nhỏ từ từ NH₃ vào AgNO₃ đến khi kết tủa vừa tan hết (thuốc thử Tollens).',
      'Thêm vài giọt acetaldehyde, ngâm ống vào cốc nước nóng khoảng 5 phút, không lắc.',
    ],
    hienTuong: 'Thành ống nghiệm phủ một lớp bạc sáng như gương.',
    giaiThich: 'CH₃CHO + 2[Ag(NH₃)₂]OH → CH₃COONH₄ + 2Ag↓ + 3NH₃ + H₂O. Aldehyde bị oxi hoá; ketone không có H gắn vào C=O nên không phản ứng.',
    anToan: ['Pha thuốc thử Tollens tới đâu dùng tới đó, đổ bỏ ngay sau thí nghiệm: để lâu có thể tạo hợp chất dễ nổ.', 'AgNO₃ làm đen da.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b23-cuoh2', lessonId: 'bai-23', sgkTrang: 141,
    ten: 'Oxi hoá aldehyde bằng Cu(OH)₂ trong môi trường kiềm',
    mucDich: 'Nhận biết aldehyde bằng copper(II) hydroxide khi đun nóng.',
    hoaChat: ['Dung dịch CuSO₄ 5 %', 'Dung dịch NaOH 10 %', 'Dung dịch acetaldehyde 5 %'],
    dungCu: ['Ống nghiệm', 'Đèn cồn'],
    cachLam: ['Trộn khoảng 0,5 mL CuSO₄ với 1 mL NaOH để tạo Cu(OH)₂.', 'Thêm khoảng 1 mL acetaldehyde, đun nhẹ trên đèn cồn.'],
    hienTuong: 'Kết tủa xanh lam chuyển dần sang đỏ gạch.',
    giaiThich: 'CH₃CHO + 2Cu(OH)₂ + NaOH → CH₃COONa + Cu₂O↓ (đỏ gạch) + 3H₂O (t°). Aldehyde khử Cu(II) thành Cu(I).',
    anToan: ['Đeo kính khi đun dung dịch kiềm; hướng miệng ống nghiệm ra xa người.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b23-iodoform', lessonId: 'bai-23', sgkTrang: 142,
    ten: 'Phản ứng tạo iodoform',
    mucDich: 'Nhận biết hợp chất có nhóm CH₃CO– (methyl ketone).',
    hoaChat: ['Dung dịch I₂ bão hoà trong KI', 'Dung dịch NaOH 2 M', 'Acetone'],
    dungCu: ['Ống nghiệm'],
    cachLam: ['Trộn khoảng 2 mL dung dịch I₂/KI với 2 mL NaOH, thêm khoảng 0,5 mL acetone, lắc.'],
    hienTuong: 'Xuất hiện kết tủa màu vàng.',
    giaiThich: 'CH₃COCH₃ + 3I₂ + 4NaOH → CHI₃↓ (iodoform, vàng) + CH₃COONa + 3NaI + 3H₂O.',
    anToan: ['Acetone dễ cháy; đeo kính khi dùng NaOH.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b24-tinh-acid', lessonId: 'bai-24', sgkTrang: 149,
    ten: 'Tính acid của acetic acid',
    mucDich: 'Acetic acid có đủ tính chất của một acid.',
    hoaChat: ['Dung dịch CH₃COOH 10 %', 'Dung dịch Na₂CO₃ 10 %', 'Bột magnesium', 'Giấy quỳ tím'],
    dungCu: ['Ống nghiệm'],
    cachLam: ['Nhỏ CH₃COOH lên giấy quỳ.', 'Cho bột Mg vào 1–2 mL CH₃COOH.', 'Cho 1–2 mL CH₃COOH vào 1–2 mL Na₂CO₃.'],
    hienTuong: 'Quỳ hoá đỏ; bột Mg tan dần, có khí không màu; ống Na₂CO₃ sủi bọt khí không màu.',
    giaiThich: '2CH₃COOH + Mg → (CH₃COO)₂Mg + H₂↑. 2CH₃COOH + Na₂CO₃ → 2CH₃COONa + CO₂↑ + H₂O.',
    anToan: ['Dùng dung dịch loãng; không để bột Mg gần lửa.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b24-ester-hoa', lessonId: 'bai-24', sgkTrang: 150,
    ten: 'Phản ứng ester hoá — điều chế ethyl acetate',
    mucDich: 'Điều chế ethyl acetate từ acetic acid và ethanol.',
    hoaChat: ['Ethanol', 'Acetic acid tinh khiết', 'H₂SO₄ đặc', 'Dung dịch NaCl bão hoà'],
    dungCu: ['Ống nghiệm', 'Nồi cách thuỷ', 'Tủ hút'],
    cachLam: ['Trộn khoảng 2 mL ethanol, 2 mL acetic acid và 1 mL H₂SO₄ đặc, đun cách thuỷ ở 60–70 °C khoảng 5 phút.', 'Để nguội, thêm khoảng 5 mL NaCl bão hoà.'],
    hienTuong: 'Chất lỏng tách hai lớp; lớp ester nổi lên trên, có mùi thơm.',
    giaiThich: 'CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O (H₂SO₄ đặc, t°). H₂SO₄ đặc vừa xúc tác vừa hút nước làm cân bằng chuyển dịch sang phải. Ester ít tan trong nước muối, nhẹ hơn nên nổi lên.',
    anToan: ['H₂SO₄ đặc và acetic acid tinh khiết gây bỏng; ethanol, ester dễ cháy: làm dưới sự hướng dẫn của giáo viên, dùng nồi cách thuỷ, đeo kính và găng.'],
    noiLam: 'phong-thi-nghiem', daDuyet: false,
  },
  {
    id: 'b24-giam-baking-soda', lessonId: 'bai-24',
    ten: 'Giấm và baking soda thổi phồng bóng bay',
    mucDich: 'Thấy acetic acid mạnh hơn carbonic acid, sinh khí CO₂.',
    hoaChat: ['Giấm ăn', 'Baking soda (NaHCO₃)'],
    dungCu: ['Chai nhựa', 'Bóng bay', 'Phễu nhỏ'],
    cachLam: ['Cho giấm vào chai, cho baking soda vào bóng bay.', 'Chụp bóng lên miệng chai rồi dựng bóng cho baking soda rơi xuống.'],
    hienTuong: 'Sủi bọt mạnh, bóng bay phồng lên.',
    giaiThich: 'CH₃COOH + NaHCO₃ → CH₃COONa + CO₂↑ + H₂O. Acid mạnh hơn đẩy acid yếu hơn (H₂CO₃ → CO₂ + H₂O) ra khỏi muối.',
    anToan: ['An toàn — đồ dùng trong bếp. Không nếm hỗn hợp.'],
    noiLam: 'tai-nha', daDuyet: false,
  },
];
